### ISSUE TITLE
一鍵凍結的應用不一定會出現在下拉選單中

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#2]
大部分應用解凍後會出現在下拉選單中，方便一鍵凍結外，還能知道哪些應該是被解凍的。但目前使用下，少數幾個應用解凍後不會出現在選單中。

另外 查看模式、快捷方式與單擊選單中，建議可以將目前的設定用顏色或符號來區別，這樣可以知道目前是使用哪個選項。

還有一個BUG，就是列表中的應用要是解凍或凍結，藍/白色的點不會立即改變，這樣無法知道是否已變成另一種狀態。

**Comment by Playhi** [comment]
> 少數幾個應用解凍後不會出現在選單中

是指那些呢，我這沒有發生類似的情況。

> 另外 查看模式、快捷方式與單擊選單中，建議可以將目前的設定用顏色或符號來區別，這樣可以知道目前是使用哪個選項。

這個感覺沒有必要誒，都是用戶設置的，應該清楚的。

> 還有一個BUG，就是列表中的應用要是解凍或凍結，藍/白色的點不會立即改變，這樣無法知道是否已變成另一種狀態。

這個問題一直沒弄，在忙別的。這是在計劃中的，後面會處理的。

**Comment by delphinuz** [comment]
>>少數幾個應用解凍後不會出現在選單中
> 是指哪些呢，我這沒有發生類似的情況。
目前為止有google play與telegram x，但剛剛試了一下，telegram x又可以了。

>>    還有一個BUG，就是列表中的應用要是解凍或凍結，藍/白色的點不會立即改變，這樣無法知道是否已變成另一種狀態。
>已經基本解決了
好的，我再測試看看。

**Comment by delphinuz** [comment]
更新到4.1，google play已出現在下拉選單中，所以可以close了。
