### ISSUE TITLE
關於3個圖示与圖示長按

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#27]
本以3個圖示代表不同功能，但試了一下都是開伵freezeyou。是否可以像greenify一樣，一個是一鍵凍結，一個是一鍵解凍？或是由使用者自行設定就更方便了。

另外長按圖示也許也能加入一鍵凍結等功能（或是放在下拉選單裡）。

**Comment by Playhi** [comment]
長按圖標已經有一鍵凍結、一鍵解凍的可選項了（需要桌面支持）。
三個圖標是同一個功能，一鍵凍結、一鍵解凍可以在軟件中創建桌面快捷方式的。

delphinuz <notifications@github.com> 于 2018年7月30日周一 14:24写道：

**Comment by delphinuz** [comment]
>  長按圖標已經有一鍵凍結、一鍵解凍的可選項了（需要桌面支持）。 
剛試一下又可以了，本來不行才寫在這裡。

> 三個圖標是同一個功能，一鍵凍結、一鍵解凍可以在軟件中創建桌面快捷方式的。
比較好奇同一功能使用三個圖示的意義是？若是使用者可以選擇偏好的圖示，是否可以設定中3選1即可。

另外安裝了google map，發現與google paly一樣，不定時會被解凍，下拉選單中也沒看到凍結的選項。

**Comment by Playhi** [comment]
設置中的確是可以三選一的，也可以三選二，也可以三選零，通過撥號盤啟動（需要撥號盤支持）。
ROOT模式被解凍可能是因為對應軟件被更新（覆蓋安裝）過了。

delphinuz <notifications@github.com> 于 2018年7月31日周二 10:58写道：

**Comment by delphinuz** [comment]
之前用空調狗是没發生這問題，即使凍結google play，然後開啟google photo，google play仍是凍結的。

自動更新都已關閉。

另外這些自動解凍的，在下拉選擇也不會出現，所以FreezeYou也不知道（或是有相關的broadcasts?)

我找個時間測試一下。
