### ISSUE TITLE
查看方式臭蟲與建議

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#40]
臭蟲：之前有提過，好像曾改善了，但昨天更新又出現了，就是狀態更改時（像是自動凍解），列表中的應用狀態不會更新。

建議：目前單擊已可以設定為固定功能，也許可以將之前的選單改為長按。

**Comment by Playhi** [comment]
狀態不更新的情況已經發現了，會進行修復的。

> 建議：目前單擊已可以設定為固定功能，也許可以將之前的選單改為長按。

並沒有理解，可否再詳細描述一下呢？

**Comment by delphinuz** [comment]
> 並沒有理解，可否再詳細描述一下呢？
在查看模式下，使用者要對應想要變動的，不是凍結就是解凍。所以內定單擊應直接改為自動凍解，不需要再有自動凍結與自動解凍。選擇動作可改為對應用長按。

這樣，選單中可以減少“單擊功能”，“更多設定”裡也不需要”保存單擊功能狀態“。單擊與長按就可以達到原本所有的功能。

**Comment by Playhi** [comment]
目前還是現在這樣吧，免得到時又有用戶說這個BUG那個BUG的，全局操作統一就不至於搞不清了，況且目前整個操作流程並不算太復雜，保存功能在用戶詳細設置的時候也能輕易發現的。

**Comment by delphinuz** [comment]
也可以，只是用不順手。

若我需要選單方式，還要進設定調整，比如將應用加入一鍵xx，調整後再回到主畫面，設定應用加入一鍵xx，设定完，再進選單改為原本的單擊功能。不妨試著做這件事，就可體會目前的操作不太方便。

主要是我的建議，反而是簡化了操作，也可以簡化設定的畫面，有機會還是希望參考看看。

**Comment by Playhi** [comment]
勾選保存以後不管如何切換界面，單擊功能選的哪個就還是哪個的，重啓FreezeYou也不變的，除非再調整單機功能的設定，或是取消保存單擊功能的勾子。
（我們是不是溝通上出現理解偏差了）

**Comment by Playhi** [comment]
單擊功能後面還會加上 加入一鍵凍結和一鍵解凍、離開凍結的選項的

**Comment by delphinuz** [comment]
請試試以下程序：
1 想單擊解凍某應用(a)。
2 希望將此應用(a)加到一鍵解凍。
3 應用(a)用完了，希望單擊將此應用凍結。
4 突然想將此應用(a)加个捷徑到桌面。

請試試目前的設定方法，是不是很要繁瑣才能完成。

若使用我的建議：
1 單擊。(因已凍解，所以執行解凍）
2 長按->選擇“加到一鍵解凍”
3 單擊。（因已解凍，所以執行凍結）
4 長按->選擇“增加捷經到桌面”
以上動作完全在同一畫面，對同一行應用單擊與長按即可完成，不用再叫出選單改變單擊。

> 勾選保存以後不管如何切換界面，單擊功能選的哪個就還是哪個的，重啓FreezeYou也不變的，除非再調整單機功能的設定，或是取消保存單擊功能的勾子。

這個沒有問題的。
但如果使用我的建議，這個功能都可以拿掉，因為我的建議可簡化這些操作與設定。

**Comment by Playhi** [comment]
> 1 想單擊解凍某應用(a)。
2 希望將此應用(a)加到一鍵解凍。
3 應用(a)用完了，希望單擊將此應用凍結。
4 突然想將此應用(a)加个捷徑到桌面。

這種場景一般用戶遇到的幾率很小的吧，桌面快捷什麼的基本也就這麼些應用程序，第一次添加過之後往往只有新安裝的才需要了，一鍵凍結一鍵解凍也是同樣，如果經常需要凍結解凍的，通過桌面快捷操作是比較方便的，而且還有通知欄快捷可以用。

確實發生的話：
- 可以長按以後先做2再做1
- 用完以後要凍結的話，可以加入離開凍結裏。

**Comment by delphinuz** [comment]
好，我再熟悉這樣的操作，這樣應該就沒什麼大問題了。
