### ISSUE TITLE
重開機後已解凍的應用不會在通知欄裡

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#55]
應不算bug，算是新加功能？

若將應用解凍，通知欄會出現凍結應用。但如果重開機，通知欄的凍結應用就沒了。

建議FreezeYou開機載入時，可以檢查目前的process是否包括已解凍應用，如果有，可在
通知欄裡再出現凍結應用的通知。

**Comment by Playhi** [comment]
之前（一個月內吧）的版本已經加入這個功能了看下是不是FreezeYou被禁止開機自啓動了吧

**Comment by delphinuz** [comment]
> 之前（一個月內吧）的版本已經加入這個功能了看下是不是FreezeYou被禁止開機自啓動了吧

看一下，是被關閉了（但之前也沒禁止？）。打開重新開機，通知欄是有未凍結的應用。

但怪的是，解凍的Google Play與Google Photo沒出現在通知欄。

**Comment by Playhi** [comment]
不是通過FreezeYou解凍的是不會出現在通知欄的

delphinuz <notifications@github.com> 于 2018年8月28日周二 06:59写道：

**Comment by delphinuz** [comment]
> 不是通過FreezeYou解凍的是不會出現在通知欄的

以為有在一鍵凍結的也會在通知欄裡。

Google Play是自動解凍（被哪個app解凍不知），也有放在一鍵凍結，但怎麼都不會出現在通知欄。
