### ISSUE TITLE
Suggestion: Add URL Scheme support

### ISSUE THREAD

**Issue by CreeperLin** [Playhi/FreezeYou#79]
thought it would be convenient to freeze/unfreeze by using url scheme like freezeyou://freeze and such. XD

**Comment by Playhi** [comment]
Any problems about the issue, please reopen the issue.

**Comment by CreeperLin** [comment]
Is it possible to freeze or unfreeze apps using different URI and without a dialog? Or is it unsafe? Thanks!

**Comment by Playhi** [comment]
It is possible, but duo to the safety reason, when it is the first time an application requests to use this feature, the user authorization is still required.
