### ISSUE TITLE
關於凍結/解凍的過渡動畫

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#9]
不知這動畫可以取消嗎？或是放到背景跑，完成或失敗可以再用訊息提示。

有時正使用某個應用，然後下拉選擇想凍結某個解凍的應用，然後畫面就跳到凍結動畫，接著就回到主頁面，還要自己手動切換回原本的應用。

另外google play有時仍不會出現在下拉選單中。telegram x會被自動解凍（？），我也是看到新訊息通知，才知道telegram x已在解凍的況態。

**Comment by delphinuz** [comment]
> 這個我大概也得寫個“？”了，看看已安裝的其他軟件有沒有解凍tg吧。

之前用其它凍結應用沒發生過。不過沒關係，我再觀察一下，因為發生二次了，才覺得怪。
不過google play不時不會出現在下拉選單中，即使是經過解凍來開啟。

> 動畫目前是給ROOT模式準備的，免ROOT正常情況不啓動應用的話動畫是一閃而過的，若啓動，會等待被啓動應用出現後消失。

我這是root的。所以都要再手動回到之前的應用。如果可以用訊息顯示解凍/凍結情況，而不影響目前的使用，那就方便多了。

**Comment by Playhi** [comment]
ROOT模式的話，在凍結以後更新對應應用程序會導致解凍的。
返回桌面這個不是我想這樣的，後面會試着解決。

**Comment by delphinuz** [comment]
> ROOT模式的話，在凍結以後更新對應應用程序會導致解凍的。
> 返回桌面這個不是我想這樣的，後面會試着解決。

看這樣會不會好一些：

1. 正在使用應用A，下拉選單，點擊凍結應用A，回到桌面並且背景凍結應用A。使用者可以繼續操作（比如開啟應用B)，應用A凍結完成後，彈出訊息表示成功（或失敗）。

2. 正在使用應用B，下拉選單，點擊凍結應用A，選單消失回到應用B，使用者可繼續操作應用B。背景凍結應用A，完成後出現彈出訊息表示成功（或失敗）。

**Comment by Playhi** [comment]
回桌面這邊有點亂，我現在似乎還沒法阻止他跑桌面去[心情復雜]，讓我再試試去。
動畫的話ROOT模式這樣轉圈也只是臨時方案，後面會設法調整。

**Comment by delphinuz** [comment]
這個不急，就當做是enhance，有機會再修改即可。

**Comment by Playhi** [comment]
好的，我會繼續關注的。
翻譯現在在 https://crowdin.com/project/freezeyou 啦，不用發郵件提交啦

**Comment by delphinuz** [comment]
> .【调整】通知栏冻结解冻快捷方式立即冻结现已不再回到桌面；

測試6.0已不回桌面，若已在某應用中很方便，不會再跳回桌面，還要手動回到原應用。

不過解凍部分的過渡畫面，還是會出現在Recents中，這部分解決就完美了。

**Comment by Playhi** [comment]
解冻的是之前故意设置的，默认最多保存3个，如果很不喜欢的话，我看看能不能加个开关

delphinuz <notifications@github.com> 于 2018年8月15日周三 21:20写道：

**Comment by delphinuz** [comment]
> 解冻的是之前故意设置的，默认最多保存3个，如果很不喜欢的话，我看看能不能加个开关

因為會在總覽(Recents)裏面出現，不小心按到的話，凍結的應用就不小心被解凍開啟，只能手動刪除。

若是為了測試用，應該可以加個開關來Debug，打開就會保留一些Debug相關的訊息。

**Comment by Playhi** [comment]
如果是用的桌面快捷解凍應用的話，自6.0開始若設置中開啓了快捷方式立即解凍並啓動，是不會在recents顯示的，如果發現最近任務中存在的話應該是之前版本使用時遺留的，劃掉即可。

**Comment by delphinuz** [comment]
測試一下，Recents已無，那這問題可以close了。
