### ISSUE TITLE
簡化訊息顯示

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#91]
選單裡的 “凍結/解凍/啓動“, 可以視應用的情況變化。

若是已凍結，則顯示““解凍/啓動“，已解凍則顯示 ”凍結/啓動“。

不是很關鍵的問題，不一定要變動。

**Comment by Playhi** [comment]
這個應該也算是歷史遺留了，先前版本在彈窗可選 凍結/解凍/啓動 （還沒去除無必要項）的時候是這樣寫的，現在看來也不需要了，後面應該會做一些變更了。

**Comment by Playhi** [comment]
若還有有關該項 issue 的問題，歡迎重新打開它。
