### ISSUE TITLE
應用列表更新問題

### ISSUE THREAD

**Issue by delphinuz** [Playhi/FreezeYou#92]
將FreezeYou備份後於其他手機還原，重新開啟FreezeYou，一鍵凍結的應用仍是原手機上的應用。
可考慮對於一鍵凍結或一鍵解凍的列表，加個清除(purge)功能，就是將沒有的應用移除。
類似對快取的清除，但是作用於一鍵凍結或一鍵解凍的列表。

**Comment by Playhi** [comment]
目前可以多選然後移出，暫時沒有類似“一鍵清理”的能力，之後可能會加入。

**Comment by Playhi** [comment]
目前已經可以在 更多設置 - 管理空間 中進行一鍵移除了。
先關閉這個 issue 了，如有問題，歡迎再次打開它。
